// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN95SBgoqJXKsNq6goW1va6TMzcL1SAmA',
    appId: '1:1049248898445:web:a562e541285fd56ffff1c4',
    messagingSenderId: '1049248898445',
    projectId: 'pumpn-app',
    authDomain: 'pumpn-app.firebaseapp.com',
    storageBucket: 'pumpn-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1xZHtWM4SBe8MttxsWdYziaJ0eKD0NBU',
    appId: '1:1049248898445:android:c1daa8f1448e59b7fff1c4',
    messagingSenderId: '1049248898445',
    projectId: 'pumpn-app',
    storageBucket: 'pumpn-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsz6b2sGwrPqrM1nxxFto-cVl0N2AY4XE',
    appId: '1:1049248898445:ios:70a97fba9b18c355fff1c4',
    messagingSenderId: '1049248898445',
    projectId: 'pumpn-app',
    storageBucket: 'pumpn-app.appspot.com',
    iosClientId: '1049248898445-vjhnuk3r97v2ikmbgcvjko1ack0po93p.apps.googleusercontent.com',
    iosBundleId: 'com.naman.pumpn.pumpn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsz6b2sGwrPqrM1nxxFto-cVl0N2AY4XE',
    appId: '1:1049248898445:ios:4ab7ffb12790a36dfff1c4',
    messagingSenderId: '1049248898445',
    projectId: 'pumpn-app',
    storageBucket: 'pumpn-app.appspot.com',
    iosClientId: '1049248898445-9k8bbdh007bvbs5hmv3rh5t11v820mo7.apps.googleusercontent.com',
    iosBundleId: 'com.naman.pumpn.pumpn.RunnerTests',
  );
}
